### ISSUE TITLE
Game Crash / World Load crash

### ISSUE THREAD

**Issue by BrewAndCode** [CJ-MC-Mods/Overloaded#12]
I initially thought this was a problem with Actually Additions auto-breaker; but it seems to be Overloaded.  I can replicate this repeatedly.

Overloaded version:  0.0.17
Actually Additions version:  1.10.2-r105
Forge: 12.18.3.2297

Steps to replicate:

Create flat world

Drop AA auto-breaker. 

Place birch planks in front of auto breaker.

Boom; crash. due to com.cjm721.overloaded.common.item.functional.ItemMultiTool

logs attached
[crash-2017-05-22_11.53.52-server.txt](https://github.com/CJ-MC-Mods/Overloaded/files/1019464/crash-2017-05-22_11.53.52-server.txt)
[crash-2017-05-22_11.42.33-server.txt](https://github.com/CJ-MC-Mods/Overloaded/files/1019465/crash-2017-05-22_11.42.33-server.txt)

**Comment by cjm721** [comment]
Fixed by commit #2d1a2f3
