### ISSUE TITLE
Crash/nullpointer when hooking fluid external storage adapter(RS) to infinite fluid container

### ISSUE THREAD

**Issue by BrewAndCode** [CJ-MC-Mods/Overloaded#13]
placed empty infinite fluid container, put RS external storage adapter on, set to fluid mode. 

There was no fluid in tank

connected RS adapter to network via cable; crash.  

log
[crash-2017-05-24_02.36.03-server.txt](https://github.com/CJ-MC-Mods/Overloaded/files/1024605/crash-2017-05-24_02.36.03-server.txt)

**Comment by cjm721** [comment]
Fixed by #c892a16
