### ISSUE TITLE
Item names not appearing in 1.10.2

### ISSUE THREAD

**Issue by BrewAndCode** [CJ-MC-Mods/Overloaded#14]
I know; I know.  it's an older versions ;)  works great in 1.11.2 but in 1.10.2 MC can't find the item name so you're getting the typical overloaded.item.yada_yada_yada as the name when you inspect, hover, etc.

**Comment by BrewAndCode** [comment]
and sorry for being a drag lately :)  just really loving the items in the mod.  I'm using them as  late game quest rewards in HQM; especially the infinite barrels.

**Comment by cjm721** [comment]
Its fine. Did not think I would have this much to change from 1.11.2 back to 1.10.2. The real version I am keeping up us 1.11.2 and 1.10.2 was just something I did in less then an hour.

Fixed by #9d9fb93
