### ISSUE TITLE
Multi Tool Issues In Creative Mode

### ISSUE THREAD

**Issue by TeetoKaziim** [CJ-MC-Mods/Overloaded#17]
In creative mode, the multitool cannot break bedrock, and behaves strangely while trying to do so: 

At range, things are the most normal: It gives the "this block is unbreakable" message and fails to break it. Inside your normal reach range however, things are a bit stranger: The bedrock displays in world as broken, but the tool still gives the message, and the bedrock block actually still exists as a ghost block that will reappear if you close and reopen the world, or cause the chunk to unload then reload.

Less problematic is that the multitool deducts blocks from your inventory when placing in creative mode, and still requires energy. Pretty easy to work around since you're already in creative mode, and can just spawn in blocks and some kind of energy source for the tool, but still not the expected behavior precedent set by other mods' items.

All in all loving what I'm seeing here though, thanks a 2^63 - 1!

**Comment by cjm721** [comment]
What version are you using? 18+ already changed how it works on creative with the invisible blocks.(still requires power, but that will be changed in 20)

**Comment by cjm721** [comment]
What version are you using? 18+ already changed how it works on creative with the invisible blocks.(still requires power, but that will be changed in 20)

**Comment by TeetoKaziim** [comment]
Aw shoot I'm still in 0.0.17 on minecraft 1.10.2, sorry for not including that, I shouldn't be making issues this time of morning.

**Comment by kohlth** [comment]
slow clap (just kiding)

**Comment by cjm721** [comment]
Closing as fixed in V18(Invisble Blocks) V20(Power Usage).

Note:
1.10.2 is not my targeted environment I only update it about once a month (if that) so you won't see the changes for another two weeks or so
