### ISSUE TITLE
overloaded Armour issues 

### ISSUE THREAD

**Issue by kohlth** [CJ-MC-Mods/Overloaded#18]
#### Overloaded Version: 0.0.24

overloaded Armour glitches out and causes player to be stuck in one place after taking damage if Armour runs out of power , only solution is teleportation between dimensions

**Comment by kohlth** [comment]
additon:

seems to glitch even when Armour has full power if its a effect like wither

**Comment by cjm721** [comment]
Not able to replicate using given information.

**Comment by kohlth** [comment]
sorry was not on much

**Comment by kohlth** [comment]
was using a nether star generator and i got withered, and got stuck in place and the time till it stopped 
was stationary at 20

**Comment by cjm721** [comment]
Tried with with single and several NSG on SP/MP and could not replicate.

**Comment by cjm721** [comment]
Closing as no more info provided and last commit  fixed a CME that may have been related to this (had different effect on the player but was caused in the same manner)
