### ISSUE TITLE
Player Interface

### ISSUE THREAD

**Issue by sironin** [CJ-MC-Mods/Overloaded#19]
Bug: When connected to rf power, does not charge rf items inside the bound player (including multi-tool and multi-armor pieces).
Expected: Player gains power charging capability

**Comment by cjm721** [comment]
Not a bug, might make a different block to have some effect like that.

**Comment by cjm721** [comment]
Need a better name (`Energy Injector Chest` right now), but I make a Block that can inject RF into items that are inside containers.
