### ISSUE TITLE
I would much like to check out your mod and am using 1.10.2 version of Minecraft.

### ISSUE THREAD

**Issue by Nastywar** [CJ-MC-Mods/Overloaded#2]
However I keep getting errors as the launcher tries to load the game. Everything works as long as your mod is not in the mods folder. I have tried with all other mods removed also. So it can't be a compatibility issue.
I have tried all the 3 current downloads for the mod with the same result.
I am using Forge version 8.0.99.99

**Comment by sironin** [comment]
Could you post what pack (if any) you're using or a crash log?  8.0.99.99 is actually the modloader version, not the forge version.

**Comment by cjm721** [comment]
Overloaded also requires Compat Layer (It is marked as a dependency in Curse but not in the mod yet)

https://minecraft.curseforge.com/projects/compatlayer

**Comment by Nastywar** [comment]
Forge 1.10.2-12.18.3.2185
No mod packs. 
Like I said I tried doing this without any mods just overloaded compatlayer... only and it keeps telling me it looks like you are using an unsupported modified version of the game and when I click on show more details it says the game crashed Wireless initializing game error: java.lang.NullPointerException: Initializing game



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by Nastywar** [comment]
Also I have compatlayer 1.10-0.2.5 



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by cjm721** [comment]
Can you upload the crash report or the full log?

Sent from my HTC

----- Reply message -----

**Comment by cjm721** [comment]
@Nastywar I figured it out. Use a more recent forge. I am running against 2254 but I know it works as far back as 2221 but will not work with the last release branch of forge (2185). I will add it in the dependencies in the next release to make sure no one else comes across this.

**Comment by Nastywar** [comment]
Ok it works on the 2272 Forge. I have a small request. There are a lot of mods out there that give you a creative energy source ect... and I refuse to use them due to the fact that I have mods that run quarries 24/7 and have more resources than I know what to do with. If you could make it to where the generator actually has a fuel source that would be awesome. It could still be infinite and the capacitor can still be infinite and I would be fine with that but I would like for the generator to actually burn fuel. There was a mod in 1.9.4 called mrFusion... in a created RF using the EMC values of the various Minecraft items but there are hardly any other mods for that version of Minecraft so I don't use it but I would love to be able to. Maybe you could incorporate something of that nature into your mod



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by cjm721** [comment]
Closing this issue has your problem has been solved.

As for the Creative Generator. Its name starts with Creative because that is the only way you should be able to get it. Eventually I will have some real generators but I needed something to test the capacitor against which is why I made that block.

**Comment by Nastywar** [comment]
I don't know about the conduits from Ender IO because I don't have it installed it causes me to lag a lot. So I use flux Networks and Link it to my draconic evolution ... and I noticed that the little flux plugs do not attach



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by cjm721** [comment]
Plugs will not directly correct to infinity capacitors (because Plugs don't pull power out of storage). Have to go through an energy extractor first (new block added in 0.0.7 to deal with mods that don't have power pulling capability). Flux Points should have no issue putting power directly into the infinity capacitors.

**Comment by Nastywar** [comment]
The flux plugs is what you attach to a generator so that the power can go to your power bank for whatever mod you're using in my case draconic evolution. flux points or what is used to retrieve that power and you attach that to whatever machine you're using. What I'm trying to say is that neither of them will attach to your capacitor Bank block. I have no way to get power out. I could put Power in by sitting it next to generators but then I would need a couple hundred of them spread out. I was just hoping you could make it possible for the plugs and points to be able to connect and of course down the road like you already stated to get some generators that actually burn fuel. Just some ideas dude I'm trying to help you make your mod good too because I want it to be good


Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by cjm721** [comment]
On version 0.0.9 flux plugs/points work fine (for both MC version 1.11.2 and 1.10.2). If they aren't working on an older version I don't why as that code has not changed since 0.0.5

**Comment by cjm721** [comment]
![image](https://cloud.githubusercontent.com/assets/2738614/25064680/3257ef40-21cd-11e7-9f8a-c14b7c2193a4.png)
![image](https://cloud.githubusercontent.com/assets/2738614/25064681/37bac93a-21cd-11e7-98f0-a9670676a89a.png)
![image](https://cloud.githubusercontent.com/assets/2738614/25064684/3b4276d4-21cd-11e7-9f60-ff55cd925e2d.png)
