### ISSUE TITLE
Server side Crash Caught exception from Overloaded

### ISSUE THREAD

**Issue by IchigoGames** [CJ-MC-Mods/Overloaded#3]
was testing mods on test server before update and i got this crash.

minecraft 1.11.2
Forge 2282
Overloaded-1.11.2-0.0.8

crash report https://pastebin.com/DMEy1r2g

server log https://www.dropbox.com/s/v6itife5i4k74wv/fml-server-latest.log?dl=0

**Comment by IchigoGames** [comment]
singeplayer bug as well When i try load a existing single player world one i had a copy of wont load with mod will load without as this is a loading loading issues i have no report i can send for this bug if theres something you need to me to send to fix this let me know.

**Comment by cjm721** [comment]
Closing as fixed in 0.0.9 and talked about it on TS
