### ISSUE TITLE
[Question] Overloaded for 1.10.2

### ISSUE THREAD

**Issue by accessdenied0** [CJ-MC-Mods/Overloaded#5]
Greetings Overloaded-team,

I'm using your mod in 1.10.2 for a while now and were awaiting new updates for it...
Because it gets only updated for 1.11.2. I came here to ask if it get any new update to 1.10.2 in the future or not? 

Because the half finished mod (in 1.10.2) doesn't seem worth keeping in my (private) pack.

Thank you in any case for maintaining and developing this mod.

access_denied

**Comment by braingkk** [comment]
We originally wanted the mod to work for both 1.10 and 1.11, but as we progressed, we realized it would be a huge amount of work to support both, as many things do not work the same across versions.

an exact quote from CJ [our coder] can be found[ here](https://minecraft.curseforge.com/projects/overloaded#c4)

**Comment by cjm721** [comment]
I might push out an update for 1.10.2 but with reduced feature set. I won't keep 1.10.2 updated weekly but every once and a while spend an hour max merging basic features over.

**Comment by accessdenied0** [comment]
Thank you for your time and effort. I appreciate that. Maybe some day it is the time to move on to 1.11.2 for me as well. But a lot of the mods I usually want to play with aren't updated yet.

**Comment by cjm721** [comment]
I know that feeling just wanted to stay ahead of the curve so when I am done I don't have to play catch up

**Comment by cjm721** [comment]
Took me 45 minutes including testing:
https://minecraft.curseforge.com/projects/overloaded/files/2419599

I have no clue how buggy it will be.

**Comment by cjm721** [comment]
Closing Ticket. If you find issues in the 1.10.2 free feel to post them.
